### ISSUE TITLE
Curious about default values

### ISSUE THREAD

**Issue by Selur** [dnjulek/vapoursynth-chromanr#1]
Is there a reason why the default values here
thres=4, threy=20, threu=20, threv=20, sizew=1, sizeh=1, stepw=1, steph=1, distance=0
differ from the defaults in FFmpeg
thres=30, threy=200, threu=200, threv=200, sizew=5, sizeh=5, stepw=1, steph=1, distance=0
?

**Comment by dnjulek** [comment]
FFmpeg's default are very aggressive, basically the maximum value supported by the filter, causing a lot of damage to the image if used like this.

**Comment by dnjulek** [comment]
ah, readme is wrong here, size is not 1, it's 3, I'll fix it.

**Comment by Selur** [comment]
Thanks for clearing that up. 👍
