### ISSUE TITLE
zig build fails hash test

### ISSUE THREAD

**Issue by drfear-zz** [dnjulek/vapoursynth-chromanr#2]
Here on Linux (Manjaro):

~/dev $ git clone https://github.com/dnjulek/vapoursynth-chromanr.git

~/dev $ cd vapoursynth-chromanr

~/dev/vapoursynth-chromanr $ ls
src  LICENSE  README.md  build.zig  build.zig.zon

# all OK so far ... but then

~/dev/vapoursynth-chromanr $ zig build -Doptimize=ReleaseFast

Fetch Packages [1/1] vapoursynth... /home/tester/dev/hybrid/testing/vapoursynth-chromanr/build.zig.zon:8:21: error: hash mismatch: expected: 12208a2b305e3a3cfb509f56320d839d1a7706946ca2baa099088361a71e899461d6, found: 1220a484cd4920d0f7195946b98ec11f4b016141178fac2eebc3ac26e0fead1c41c7
            .hash = "12208a2b305e3a3cfb509f56320d839d1a7706946ca2baa099088361a71e899461d6",
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by dnjulek** [comment]
Fixed: https://github.com/dnjulek/vapoursynth-chromanr/commit/93beaea38b1075cf7fc081ead4d31e857afb6749
